FROM node:20-alpine AS base

WORKDIR /app

COPY apps/dashboard/package.json ./
RUN npm install

COPY apps/dashboard/ ./

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=base /app/public ./public
COPY --from=base /app/.next/standalone ./
COPY --from=base /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
